spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_example?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Yerevan
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#JWT
jwt:
  secret: DSFDS@!#@#$#
  expiration: 6000000
  header: Authorization