spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#JWT
jwt:
  secret: DSFDS@!#@#$#
  expiration: 6000000
  header: Authorization